# Generated by Django 3.1.5 on 2021-01-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_type', models.CharField(max_length=50)),
                ('ward_name', models.CharField(max_length=50)),
                ('ward_desc', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.liaizon')),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50)),
                ('room_desc', models.CharField(max_length=50)),
                ('tot_beds', models.PositiveIntegerField()),
                ('occupied_bed', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='Referal.liaizon')),
                ('ward', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Referal.ward')),
            ],
        ),
    ]
