# Generated by Django 3.0.5 on 2021-02-24 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0002_room_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('Specialized', 'Specialized'), ('General', 'General'), ('Primary', 'Primary'), ('Health Center', 'Health Center')], max_length=30),
        ),
    ]
