# Generated by Django 3.0.5 on 2021-03-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0004_facility_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility_user',
            name='user_type',
        ),
    ]
