# Generated by Django 3.0.5 on 2021-03-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0007_auto_20210305_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
