# Generated by Django 3.0.5 on 2021-03-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0008_auto_20210305_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='facility',
            new_name='facility_id',
        ),
    ]
