# Generated by Django 3.0.5 on 2021-03-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0010_auto_20210305_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
