# Generated by Django 3.0.5 on 2021-03-06 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0012_auto_20210306_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_mrn', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.CharField(max_length=10)),
                ('mob', models.CharField(max_length=50)),
                ('diagnosis', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('app_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.Facility_User')),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.Facility')),
            ],
        ),
    ]
