# Generated by Django 3.0.5 on 2021-03-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0013_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_desc', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.Facility_User')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.Facility')),
            ],
        ),
    ]
