# Generated by Django 3.0.5 on 2021-03-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0014_facility_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
