# Generated by Django 3.0.5 on 2021-03-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0015_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_mrn', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('patient_age', models.CharField(max_length=4)),
                ('mob', models.CharField(max_length=50)),
                ('diagnosis', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('app_date', models.DateField()),
                ('app_round', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Admitted', 'Admitted'), ('Not Available', 'Not Available')], default='Pending', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.Facility_User')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.Facility')),
            ],
        ),
    ]
