# Generated by Django 3.0.5 on 2021-03-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0016_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_mrn', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.CharField(max_length=50)),
                ('diagnosis', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.Facility_User')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Referal.Facility')),
            ],
        ),
    ]
