# Generated by Django 3.0.5 on 2021-03-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0017_appoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='department',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoint',
            name='mob',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoint',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
