# Generated by Django 3.0.5 on 2021-03-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0018_auto_20210307_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50, null=True),
        ),
    ]
