# Generated by Django 3.0.5 on 2021-03-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0019_appoint_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
