# Generated by Django 3.0.5 on 2021-03-07 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0020_auto_20210307_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='app_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
