# Generated by Django 3.0.5 on 2021-03-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0021_appoint_app_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='app_date',
            field=models.TextField(),
        ),
    ]
