# Generated by Django 3.0.5 on 2021-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0022_auto_20210309_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Waiting', 'Waiting'), ('Closed', 'Closed'), ('Not Available', 'Not Available')], default='Pending', max_length=50, null=True),
        ),
    ]
