# Generated by Django 3.0.5 on 2021-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0023_appoint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='app_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
