# Generated by Django 3.0.5 on 2021-03-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0025_auto_20210310_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='app_date',
            field=models.DateTimeField(),
        ),
    ]
