# Generated by Django 3.0.5 on 2021-03-13 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Referal', '0027_auto_20210312_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='facility',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Referal.Facility'),
            preserve_default=False,
        ),
    ]
